### ISSUE TITLE
TODOs

### ISSUE THREAD

**Issue by franra9** [brynjarmorka/ACINN_twitter_bot#7]
From last Monday, what should be done before the last assignment is:

- [x]  Create a good design sheet for the tweets. #6 (e.g. format and frequency)

- [x]  Migrate config file to generic ~/home instead of being stored in the repository 

- [x]  Change climate data format (from .csv to parquet for example)

- [x] Document and test

**Comment by brynjarmorka** [comment]
I moved the config file and changed the .csv to .gzip (a parquet compressed file)
